collections:
  drawings:
    output: true
    permalink: /drawings/:title/
  stereoscopic_images:
    output: true
    permalink: /stereoscopic-images/:title/
  scribbles:
    output: true
    permalink: /scribbles/:title
  tags:
    output: true
    permalink: /tags/:title/
permalink: pretty
